package Institue;


/**
* Institue/_EtudiantStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Institue.idl
* Wednesday, December 18, 2024 5:33:07 PM WAT
*/


// Define the interface for an Etudiant
public class _EtudiantStub extends org.omg.CORBA.portable.ObjectImpl implements Institue.Etudiant
{

  public void AjouterUneEpreuve ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("AjouterUneEpreuve", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                AjouterUneEpreuve (        );
            } finally {
                _releaseReply ($in);
            }
  } // AjouterUneEpreuve

  public String[] ListeDesEpreuves ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ListeDesEpreuves", true);
                $in = _invoke ($out);
                String $result[] = Institue.StringListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return ListeDesEpreuves (        );
            } finally {
                _releaseReply ($in);
            }
  } // ListeDesEpreuves


  // Return a list of strings
  public double CalculerLaMoyenne ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("CalculerLaMoyenne", true);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return CalculerLaMoyenne (        );
            } finally {
                _releaseReply ($in);
            }
  } // CalculerLaMoyenne

  public Institue.Livre EmprunterUnLivre (Institue.Livre book, Institue.LivreListHolder livres)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("EmprunterUnLivre", true);
                Institue.LivreHelper.write ($out, book);
                Institue.LivreListHelper.write ($out, livres.value);
                $in = _invoke ($out);
                Institue.Livre $result = Institue.LivreHelper.read ($in);
                livres.value = Institue.LivreListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return EmprunterUnLivre (book, livres        );
            } finally {
                _releaseReply ($in);
            }
  } // EmprunterUnLivre

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Institue/Etudiant:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _EtudiantStub
