package Institue;


/**
* Institue/Epreuve.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Institue.idl
* Wednesday, December 18, 2024 6:39:06 PM WAT
*/

public final class Epreuve implements org.omg.CORBA.portable.IDLEntity
{
  public String nom = null;
  public double note = (double)0;
  public double coefficient = (double)0;

  public Epreuve ()
  {
  } // ctor

  public Epreuve (String _nom, double _note, double _coefficient)
  {
    nom = _nom;
    note = _note;
    coefficient = _coefficient;
  } // ctor

  public String afficher() {
    return "Matière : " + this.nom + ", Note : " + this.note + "/20, Coeff : " + this.coefficient;
  }

  @Override
  public String toString() {
    return afficher();
  }
} // class Epreuve
