package Institue;


/**
* Institue/EtudiantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Institue.idl
* Wednesday, December 18, 2024 5:33:07 PM WAT
*/


// Define the interface for an Etudiant
public interface EtudiantOperations 
{
  void AjouterUneEpreuve ();
  String[] ListeDesEpreuves ();

  // Return a list of strings
  double CalculerLaMoyenne ();
  Institue.Livre EmprunterUnLivre (Institue.Livre book, Institue.LivreListHolder livres);
} // interface EtudiantOperations
