package Institue;


/**
* Institue/EtudiantPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Institue.idl
* Wednesday, December 18, 2024 5:33:07 PM WAT
*/


// Define the interface for an Etudiant
public abstract class EtudiantPOA extends org.omg.PortableServer.Servant
 implements Institue.EtudiantOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("AjouterUneEpreuve", new java.lang.Integer (0));
    _methods.put ("ListeDesEpreuves", new java.lang.Integer (1));
    _methods.put ("CalculerLaMoyenne", new java.lang.Integer (2));
    _methods.put ("EmprunterUnLivre", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Institue/Etudiant/AjouterUneEpreuve
       {
         this.AjouterUneEpreuve ();
         out = $rh.createReply();
         break;
       }

       case 1:  // Institue/Etudiant/ListeDesEpreuves
       {
         String $result[] = null;
         $result = this.ListeDesEpreuves ();
         out = $rh.createReply();
         Institue.StringListHelper.write (out, $result);
         break;
       }


  // Return a list of strings
       case 2:  // Institue/Etudiant/CalculerLaMoyenne
       {
         double $result = (double)0;
         $result = this.CalculerLaMoyenne ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 3:  // Institue/Etudiant/EmprunterUnLivre
       {
         Institue.Livre book = Institue.LivreHelper.read (in);
         Institue.LivreListHolder livres = new Institue.LivreListHolder ();
         livres.value = Institue.LivreListHelper.read (in);
         Institue.Livre $result = null;
         $result = this.EmprunterUnLivre (book, livres);
         out = $rh.createReply();
         Institue.LivreHelper.write (out, $result);
         Institue.LivreListHelper.write (out, livres.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Institue/Etudiant:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Etudiant _this() 
  {
    return EtudiantHelper.narrow(
    super._this_object());
  }

  public Etudiant _this(org.omg.CORBA.ORB orb) 
  {
    return EtudiantHelper.narrow(
    super._this_object(orb));
  }


} // class EtudiantPOA
